# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

image: ubuntu

pages:
  stage: deploy
  script:
    - apt-get update -qq
    - apt-get install -y -qq imagemagick zip
    - bash ./deploy-prepare.sh
    - cp -ai . /tmp/gl_pages_public
    - mv -i /tmp/gl_pages_public public
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

