variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

stages:
  - test

unittests:
  stage: test
  image: python:3.7
  before_script:
    - pip install -r requirements.txt
    - cd mysite
  script:
    - pytest tests
  cache:
    key: "$CI_PROJECT_ID__pip_cache"
    paths:
      - "$PIP_CACHE_DIR"
